
use_frameworks!
use_modular_headers!
inhibit_all_warnings!

target 'OpenIMSDKUIKit_Example' do
  pod 'OUICore', :path => '../'
  pod 'OUICoreView', :path => '../'
  pod 'OUIIM', :path => '../'
  pod 'OUICalling', :path => '../'
  pod 'OUILive', :path => '../'
#  pod 'OUIOrganization', :path => '../'
  pod 'OUIMoments', :path => '../'
  pod 'OpenIMSDK', :path => '../OpenIMSDK'
  pod 'ISEmojiView', :path => '../3rd'
  pod 'InputBarAccessoryView', :path => '../3rd'
  pod 'ZLPhotoBrowser', :path => '../3rd'
  pod 'ZFPlayer', :path => '../3rd'
#  pod 'LiveKitClient', :git => 'https://github.com/livekit/client-sdk-swift.git', :tag => '1.1.6'
  
  pod 'Localize-Swift', '~> 3.2'
  pod 'RxGesture', '~> 4.0.4'
  pod 'ProgressHUD', :git => 'https://github.com/std-s/ProgressHUD.git'
  pod 'MMBAlertsPickers'
  pod 'SGCodeTextField'
#  pod 'JXPatternLock'
  pod 'AlamofireNetworkActivityLogger'
  pod 'GTSDK', '2.7.1.0-noidfa'
 

pod "QMUIKit", '4.5.1'
pod 'SnapKit'
pod 'TangramKit'
pod 'R.swift'
pod "DynamicColor"
pod 'SDWebImage'
pod 'Moya'
#pod "HandyJSON"
pod "NSObject+Rx"
pod 'MBProgressHUD'
pod "Kingfisher"
pod 'SwifterSwift'
pod 'MJRefresh'
pod "SwiftEventBus"
#富文本框架
pod "BSText"

pod 'IQKeyboardManagerSwift'

pod 'Bugly'

pod 'Firebase/Messaging'

end

# 开启会议后有屏幕分享功能才会使用该target
target 'ScreenShareBroadcastExtension' do
#  pod 'LiveKitClient', :git => 'https://github.com/livekit/client-sdk-swift.git', :tag => '1.1.6'
#  pod 'LiveKitClient', :git => 'https://github.com/livekit/client-sdk-swift.git', :tag => '2.0.14'
#  pod 'LiveKitWebRTC', :git => 'https://github.com/livekit/webrtc-xcframework.git', :tag => '125.6422.07'
end

post_install do |installer|
  app_project = Xcodeproj::Project.open('OpenIMSDKUIKit.xcodeproj')
    app_project.native_targets.each do |target|
        target.build_configurations.each do |config|
          config.build_settings['OTHER_SWIFT_FLAGS'] = ['$(inherited)', '-D', 'COCOAPODS',
          '-D', 'ENABLE_MOMENTS', #开启朋友圈
          '-D', 'ENABLE_CALL'
          ]
        end
    end
  app_project.save
  
 installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
          config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
#          config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
          config.build_settings['ENABLE_BITCODE'] = 'NO'
          config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ""
          config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
          config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
                
          # 'ENABLE_CALL', 'ENABLE_MOMENTS', 'ENABLE_LIVE_ROOM', 'ENABLE_ORGANIZATION'
          # 开启某个功能需要更改上一级spec文件中的引用关系
          if target.name == 'OUIIM'
            config.build_settings['OTHER_SWIFT_FLAGS'] = ['$(inherited)',
            '-D', 'COCOAPODS',
            '-D', 'ENABLE_MOMENTS',
            '-D', 'ENABLE_CALL', # 开启音视频
            '-D', 'ENABLE_LIVE_ROOM' # 开启会议
#            '-D', 'ENABLE_ORGANIZATION', # 开启组织架构
            ]
          end
          
          if target.name == 'OUICore'
            config.build_settings['OTHER_SWIFT_FLAGS'] = ['$(inherited)',
            '-D', 'COCOAPODS',
            '-D', 'ENABLE_CALL', # 开启音视频
            '-D', 'ENABLE_LIVE_ROOM' # 开启会议
            ]
          end
#
#          # 如果开启组织架构，需要设置此处
#          if target.name == 'OUICoreView'
#            config.build_settings['OTHER_SWIFT_FLAGS'] = ['$(inherited)',
#            '-D', 'COCOAPODS',
##            '-D', 'ENABLE_ORGANIZATION' # 开启组织架构
#            ]
#          end
#
          if target.name == 'LiveKitClient'
              # 开启会议后有屏幕分享功能才会使用该target
              config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = "NO"
              target.build_configurations.each do |config|
                config.build_settings['OTHER_SWIFT_FLAGS'] ||= ['$(inherited)']
                config.build_settings['OTHER_SWIFT_FLAGS'] << '-enable-experimental-feature AccessLevelOnImport'
              end
            end
    end
  end
end
